### ISSUE TITLE
Fatal: initialization error : could not initialize application 

### ISSUE THREAD

**Issue by BlackTango** [aviau/linux-cheminot#7]
Salut, j'ai fait sudo make run. Voici ce qui arrive.

![screenshot from 2018-05-08 15-52-09](https://user-images.githubusercontent.com/15683321/39779731-198f31b6-52d8-11e8-909f-01f0cba1743e.png)

Nice job btw! J'ai été vraiment surpris de voir ce repo..

**Comment by mikefaille** [comment]
@BlackTango Le Openjdk de Debian semble avec du trouble avec Cheminot tandis que ça fonctionne sous Fedora 26+ avec Openjdk 8. 

Le trouble n'est toutefois pas la version de Java (ou, le no du build aka version mineur). Comme tu peux le voir dans ton message d'erreur, c'est du côté d'une politique de sécurité. Le tout est documenté ici : 
https://docs.oracle.com/javase/7/docs/technotes/guides/security/PolicyFiles.html

Dans Debian, je n'ai toutefois pas réussi à régler ce trouble qui est apparu depuis prêt d'un an avec l'image Docker de @aviau (qui fonctionnait très bien avant.). 

@BlackTango Si tu veux corriger ce bug, je peux t'aider pour te partir. Cheers!

**Comment by BlackTango** [comment]
Je crois qu'il faudrais corriger cheminot au complet. 

Merci encore, bonne journée!

**Comment by aviau** [comment]
faites juste update l'image à testing/buster, jvais le faire si personne ouvre une PR.

**Comment by mikefaille** [comment]
@aviau J'avais testé en début d'année sans succès. Je peux réessayer.

**Comment by mikefaille** [comment]
@aviau Je viens de tester avec Debian Testing et ça ne fonctionne pas plus. Je suis persuadé que le trouble c'est un bug de politique de sécurité configurable. Debian et Fedora n'ont pas les même configurations à ce niveau. Et, le Openjdk de Debian testing est plus à jour que celui de Fedora 26.

**Comment by waldo121** [comment]
J'ai fait une version du repo avec une image d'archlinux à la place de debian puisque celle de debian ne fonctionne plus depuis un petit bout.

**Comment by aviau** [comment]
Ca devrait être fixed looo
